name: Deploy React app 

on:
  push:
    branches: ["version-2025"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # If your CNAME is in the repo root (or you want to enforce it),
      # copy it into the build output so Pages serves the custom domain.
      - name: Copy CNAME into build (if present)
        run: |
          if [ -f CNAME ]; then
            cp CNAME build/CNAME
          fi
          # If you keep CNAME in public/, CRA already copies it during build.

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
